services:
  frontend:
    container_name: jointravel-front-container
    image: jointravel-front
    build:
      context: .
      args:
        - VITE_BACKEND_URL=${VITE_BACKEND_URL}
        - VITE_UMAMI_URL=${VITE_UMAMI_URL}
        - VITE_UMAMI_WEBSITE_ID=${VITE_UMAMI_WEBSITE_ID}
    ports:
      - "${APP_HOST_PORT}:3060"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - VITE_BACKEND_URL=${VITE_BACKEND_URL}
      - VITE_UMAMI_URL=${VITE_UMAMI_URL}
      - VITE_UMAMI_WEBSITE_ID=${VITE_UMAMI_WEBSITE_ID}
      - TZ=UTC
