services:
  frontend:
    container_name: jointravel-front-container
    image: jointravel-front
    build:
      context: .
      args:
        - VITE_BACKEND_URL=${VITE_BACKEND_URL}
    ports:
      - "${APP_HOST_PORT}:80"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - VITE_BACKEND_URL=${VITE_BACKEND_URL}
