services:
  frontend:
    container_name: jointravel-front-container
    image: jointravel-front
    build: .
    ports:
      - "${APP_HOST_PORT}:80"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
